title: My AI Blog
description: This blog site is dedicated to sharing AI knowledge!
theme: just-the-docs

url: https://lichahacodes.github.io/my-AI-blog/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
